"""highlight selections and follows

Revision ID: 24a274993f49
Revises: c5184dc0b3e7
Create Date: 2026-09-10 21:58:02.626010+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "24a274993f49"
down_revision: str | None = "c5184dc0b3e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "highlight_follows",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("highlight_id", sa.Integer(), nullable=False),
        sa.Column("followed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlight_follows")),
        sa.UniqueConstraint("user_id", "highlight_id", name="uq_highlight_follow_user"),
    )
    with op.batch_alter_table("highlight_follows", schema=None) as batch_op:
        batch_op.create_index("ix_highlight_follows_user", ["user_id"], unique=False)

    op.create_table(
        "highlight_selections",
        sa.Column("source", sa.String(length=16), server_default=sa.text("'live'"), nullable=False),
        sa.Column("selection_date", sa.Date(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("home_name", sa.String(length=128), nullable=False),
        sa.Column("away_name", sa.String(length=128), nullable=False),
        sa.Column("competition", sa.String(length=128), nullable=True),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("base_rate", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("coverage", sa.String(length=24), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "components_used",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "factors",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlight_selections")),
        sa.UniqueConstraint(
            "provider_event_id", "market", "outcome", "source", name="uq_highlight_fixture_market"
        ),
    )
    with op.batch_alter_table("highlight_selections", schema=None) as batch_op:
        batch_op.create_index("ix_highlight_selections_day", ["selection_date"], unique=False)
        batch_op.create_index("ix_highlight_selections_source", ["source"], unique=False)
        batch_op.create_index("ix_highlight_selections_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight_selections", schema=None) as batch_op:
        batch_op.drop_index("ix_highlight_selections_status")
        batch_op.drop_index("ix_highlight_selections_source")
        batch_op.drop_index("ix_highlight_selections_day")

    op.drop_table("highlight_selections")
    with op.batch_alter_table("highlight_follows", schema=None) as batch_op:
        batch_op.drop_index("ix_highlight_follows_user")

    op.drop_table("highlight_follows")
    # ### end Alembic commands ###
