"""stored match analyses

Revision ID: 29c502a89446
Revises: df702a23e0e0
Create Date: 2026-09-08 18:43:00.702880+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "29c502a89446"
down_revision: str | None = "df702a23e0e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_analyses",
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_event_id", sa.String(length=64), nullable=False),
        sa.Column("home_name", sa.String(length=128), nullable=False),
        sa.Column("away_name", sa.String(length=128), nullable=False),
        sa.Column("competition", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("coverage", sa.String(length=24), nullable=False),
        sa.Column("unavailable_reason", sa.Text(), nullable=True),
        sa.Column(
            "markets", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("expected_home_goals", sa.Float(), nullable=True),
        sa.Column("expected_away_goals", sa.Float(), nullable=True),
        sa.Column(
            "market_odds", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column(
            "market_probabilities",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "home_stats", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "away_stats", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "components_used",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "components_dropped",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_analyses")),
        sa.UniqueConstraint(
            "provider_name", "provider_event_id", name="uq_stored_analyses_provider_event"
        ),
    )
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.create_index("ix_stored_analyses_coverage", ["coverage"], unique=False)
        batch_op.create_index("ix_stored_analyses_kickoff", ["kickoff"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_stored_analyses_kickoff")
        batch_op.drop_index("ix_stored_analyses_coverage")

    op.drop_table("stored_analyses")
    # ### end Alembic commands ###
