"""initial schema

Revision ID: 2a6b84e1ddb1
Revises:
Create Date: 2026-09-08 00:58:34.134417+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2a6b84e1ddb1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("canonical_name", sa.String(length=160), nullable=False),
        sa.Column("normalized_name", sa.String(length=160), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("has_historical_coverage", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "external_metadata",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint(
            "sport", "country", "normalized_name", name="uq_competitions_sport_country_name"
        ),
    )
    op.create_index(
        "ix_competitions_has_historical_coverage",
        "competitions",
        ["has_historical_coverage"],
        unique=False,
    )
    op.create_table(
        "model_versions",
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "training",
                "validated",
                "promoted",
                "retired",
                "rejected",
                name="model_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "margin_method",
            sa.Enum(
                "proportional",
                "power",
                "shin",
                name="margin_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "ensemble_method",
            sa.Enum(
                "market_only",
                "log_odds_shrinkage",
                "bayesian_update",
                "residual_model",
                "weighted_average",
                name="ensemble_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "feature_set",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "validation_metrics",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("training_start", sa.Date(), nullable=True),
        sa.Column("training_end", sa.Date(), nullable=True),
        sa.Column("validation_start", sa.Date(), nullable=True),
        sa.Column("validation_end", sa.Date(), nullable=True),
        sa.Column("test_start", sa.Date(), nullable=True),
        sa.Column("test_end", sa.Date(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promotion_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "training_end IS NULL OR test_start IS NULL OR training_end < test_start",
            name=op.f("ck_model_versions_training_precedes_test"),
        ),
        sa.CheckConstraint(
            "validation_end IS NULL OR test_start IS NULL OR validation_end < test_start",
            name=op.f("ck_model_versions_validation_precedes_test"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="uq_model_versions_name_version"),
    )
    op.create_index("ix_model_versions_status", "model_versions", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "plan",
            sa.Enum(
                "free",
                "standard",
                "premium",
                name="user_plan",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="free",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("age_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("credits >= 0", name=op.f("ck_users_credits_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_index("ix_users_last_seen_at", "users", ["last_seen_at"], unique=False)
    op.create_table(
        "scans",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("model_version_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "scan_type",
            sa.Enum(
                "today",
                "next_24h",
                "next_48h",
                "custom_range",
                name="scan_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "conservative",
                "balanced",
                "aggressive",
                "research",
                name="scan_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "no_opportunity",
                "cancelled",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("credits_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("credits_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("matches_scanned", sa.Integer(), server_default="0", nullable=False),
        sa.Column("matches_unmodellable", sa.Integer(), server_default="0", nullable=False),
        sa.Column("outcomes_scanned", sa.Integer(), server_default="0", nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credits_reserved >= 0 AND credits_used >= 0",
            name=op.f("ck_scans_credits_non_negative"),
        ),
        sa.CheckConstraint(
            "credits_used <= credits_reserved", name=op.f("ck_scans_usage_within_reservation")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_scans_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_scans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_scans_user_id_idempotency_key"),
    )
    op.create_index("ix_scans_status", "scans", ["status"], unique=False)
    op.create_index("ix_scans_user_id_created_at", "scans", ["user_id", "created_at"], unique=False)
    op.create_table(
        "teams",
        sa.Column("canonical_name", sa.String(length=160), nullable=False),
        sa.Column("normalized_name", sa.String(length=160), nullable=False),
        sa.Column("short_name", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("competition_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "external_metadata",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_teams_competition_id_competitions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint(
            "sport", "country", "normalized_name", name="uq_teams_sport_country_normalized_name"
        ),
    )
    op.create_index("ix_teams_normalized_name", "teams", ["normalized_name"], unique=False)
    op.create_table(
        "wallet_transactions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_before", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "signup_bonus",
                "purchase",
                "admin_adjustment",
                "scan_reservation",
                "scan_settlement",
                "scan_release",
                "booking_code",
                "refund",
                name="transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "reserved",
                "completed",
                "released",
                "failed",
                name="transaction_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parent_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_after = balance_before + amount",
            name=op.f("ck_wallet_transactions_balance_arithmetic_consistent"),
        ),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_wallet_transactions_balance_after_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["parent_transaction_id"],
            ["wallet_transactions.id"],
            name=op.f("fk_wallet_transactions_parent_transaction_id_wallet_transactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_wallet_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_transactions")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_wallet_transactions_user_id_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_wallet_transactions_created_at"),
        "wallet_transactions",
        ["created_at"],
        unique=False,
    )
    op.create_index("ix_wallet_transactions_state", "wallet_transactions", ["state"], unique=False)
    op.create_index(
        "ix_wallet_transactions_user_id_created_at",
        "wallet_transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "booking_codes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("scan_id", sa.BigInteger(), nullable=True),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("booking_code", sa.String(length=64), nullable=True),
        sa.Column("share_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "expired",
                "failed",
                "partially_unavailable",
                name="booking_code_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "selections",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "unavailable_selections",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("expiry_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_booking_codes_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_booking_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_codes")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_booking_codes_user_id_idempotency_key"
        ),
    )
    op.create_index("ix_booking_codes_status", "booking_codes", ["status"], unique=False)
    op.create_index(
        "ix_booking_codes_user_id_created_at",
        "booking_codes",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "historical_matches",
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_match_id", sa.String(length=128), nullable=False),
        sa.Column("home_team_id", sa.BigInteger(), nullable=False),
        sa.Column("away_team_id", sa.BigInteger(), nullable=False),
        sa.Column("competition_id", sa.BigInteger(), nullable=True),
        sa.Column("season", sa.String(length=16), nullable=True),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=False),
        sa.Column("away_goals", sa.Integer(), nullable=False),
        sa.Column("half_time_home_goals", sa.Integer(), nullable=True),
        sa.Column("half_time_away_goals", sa.Integer(), nullable=True),
        sa.Column("data_version", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "home_goals >= 0 AND away_goals >= 0",
            name=op.f("ck_historical_matches_goals_non_negative"),
        ),
        sa.CheckConstraint(
            "home_team_id <> away_team_id", name=op.f("ck_historical_matches_teams_differ")
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_historical_matches_away_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_historical_matches_competition_id_competitions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_historical_matches_home_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_matches")),
        sa.UniqueConstraint(
            "provider_name",
            "provider_match_id",
            name="uq_historical_matches_provider_name_provider_match_id",
        ),
    )
    op.create_index(
        "ix_historical_matches_away_team_id_match_date",
        "historical_matches",
        ["away_team_id", "match_date"],
        unique=False,
    )
    op.create_index(
        "ix_historical_matches_home_team_id_match_date",
        "historical_matches",
        ["home_team_id", "match_date"],
        unique=False,
    )
    op.create_index(
        "ix_historical_matches_match_date", "historical_matches", ["match_date"], unique=False
    )
    op.create_table(
        "matches",
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("home_team_id", sa.BigInteger(), nullable=True),
        sa.Column("away_team_id", sa.BigInteger(), nullable=True),
        sa.Column("home_team_raw", sa.String(length=160), nullable=False),
        sa.Column("away_team_raw", sa.String(length=160), nullable=False),
        sa.Column("competition_id", sa.BigInteger(), nullable=True),
        sa.Column("competition_raw", sa.String(length=160), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "live",
                "finished",
                "postponed",
                "cancelled",
                "unknown",
                name="match_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "modellability",
            sa.Enum(
                "modellable",
                "no_historical_coverage",
                "unresolved_teams",
                "insufficient_matches",
                "unsupported_sport",
                name="modellability_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("modellability_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_matches_away_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_matches_competition_id_competitions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_matches_home_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint(
            "provider_name", "provider_event_id", name="uq_matches_provider_name_event_id"
        ),
    )
    op.create_index("ix_matches_modellability", "matches", ["modellability"], unique=False)
    op.create_index("ix_matches_start_time", "matches", ["start_time"], unique=False)
    op.create_index(
        "ix_matches_status_start_time", "matches", ["status", "start_time"], unique=False
    )
    op.create_table(
        "team_aliases",
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("alias", sa.String(length=160), nullable=False),
        sa.Column("normalized_alias", sa.String(length=160), nullable=False),
        sa.Column("external_team_id", sa.String(length=128), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "auto_confirmed",
                "manually_confirmed",
                "pending_review",
                "rejected",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)",
            name=op.f("ck_team_aliases_match_confidence_is_a_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_aliases_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_aliases")),
        sa.UniqueConstraint(
            "provider_name", "normalized_alias", name="uq_team_aliases_provider_normalized_alias"
        ),
    )
    op.create_index(
        "ix_team_aliases_external_team_id",
        "team_aliases",
        ["provider_name", "external_team_id"],
        unique=False,
    )
    op.create_index(
        "ix_team_aliases_review_status", "team_aliases", ["review_status"], unique=False
    )
    op.create_table(
        "markets",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_market_id", sa.String(length=64), nullable=False),
        sa.Column("market_name", sa.String(length=128), nullable=False),
        sa.Column("specifier", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "settled",
                "removed",
                name="outcome_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_markets_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint(
            "match_id",
            "provider_market_id",
            "specifier",
            name="uq_markets_match_id_provider_market_id_specifier",
        ),
    )
    op.create_table(
        "outcomes",
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_outcome_id", sa.String(length=64), nullable=False),
        sa.Column("outcome_name", sa.String(length=128), nullable=False),
        sa.Column("odds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "SETTLED",
                "REMOVED",
                name="outcome_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "staleness",
            sa.Enum(
                "fresh",
                "stale",
                "expired",
                name="staleness_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("odds > 1", name=op.f("ck_outcomes_odds_exceed_stake")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_outcomes_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcomes")),
        sa.UniqueConstraint(
            "market_id", "provider_outcome_id", name="uq_outcomes_market_id_provider_outcome_id"
        ),
    )
    op.create_index("ix_outcomes_staleness", "outcomes", ["staleness"], unique=False)
    op.create_table(
        "odds_snapshots",
        sa.Column("outcome_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column(
            "provider_role",
            sa.Enum(
                "reference",
                "tradeable",
                name="provider_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("odds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column(
            "snapshot_type",
            sa.Enum(
                "opening",
                "interim",
                "closing",
                name="snapshot_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("odds > 1", name=op.f("ck_odds_snapshots_odds_exceed_stake")),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["outcomes.id"],
            name=op.f("fk_odds_snapshots_outcome_id_outcomes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshots")),
    )
    op.create_index(
        "ix_odds_snapshots_outcome_id_captured_at",
        "odds_snapshots",
        ["outcome_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_odds_snapshots_provider_role_snapshot_type",
        "odds_snapshots",
        ["provider_role", "snapshot_type"],
        unique=False,
    )
    op.create_table(
        "predictions",
        sa.Column("scan_id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("outcome_id", sa.BigInteger(), nullable=True),
        sa.Column("model_version_id", sa.BigInteger(), nullable=False),
        sa.Column("tradeable_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("reference_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("market_name", sa.String(length=128), nullable=False),
        sa.Column("selection", sa.String(length=128), nullable=False),
        sa.Column("specifier", sa.String(length=64), nullable=True),
        sa.Column("odds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column(
            "margin_method",
            sa.Enum(
                "PROPORTIONAL",
                "POWER",
                "SHIN",
                name="margin_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("raw_market_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("market_prior_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("model_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("final_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("edge", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "feature_values",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)",
            name=op.f("ck_predictions_confidence_score_in_range"),
        ),
        sa.CheckConstraint(
            "final_probability > 0 AND final_probability < 1",
            name=op.f("ck_predictions_final_probability_in_range"),
        ),
        sa.CheckConstraint(
            "market_prior_probability > 0 AND market_prior_probability < 1",
            name=op.f("ck_predictions_prior_in_range"),
        ),
        sa.CheckConstraint("odds > 1", name=op.f("ck_predictions_odds_exceed_stake")),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_predictions_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["outcomes.id"],
            name=op.f("fk_predictions_outcome_id_outcomes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reference_snapshot_id"],
            ["odds_snapshots.id"],
            name=op.f("fk_predictions_reference_snapshot_id_odds_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_predictions_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tradeable_snapshot_id"],
            ["odds_snapshots.id"],
            name=op.f("fk_predictions_tradeable_snapshot_id_odds_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(op.f("ix_predictions_created_at"), "predictions", ["created_at"], unique=False)
    op.create_index("ix_predictions_match_id", "predictions", ["match_id"], unique=False)
    op.create_index(
        "ix_predictions_model_version_id", "predictions", ["model_version_id"], unique=False
    )
    op.create_index("ix_predictions_scan_id_rank", "predictions", ["scan_id", "rank"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_scan_id_rank", table_name="predictions")
    op.drop_index("ix_predictions_model_version_id", table_name="predictions")
    op.drop_index("ix_predictions_match_id", table_name="predictions")
    op.drop_index(op.f("ix_predictions_created_at"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_odds_snapshots_provider_role_snapshot_type", table_name="odds_snapshots")
    op.drop_index("ix_odds_snapshots_outcome_id_captured_at", table_name="odds_snapshots")
    op.drop_table("odds_snapshots")
    op.drop_index("ix_outcomes_staleness", table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_table("markets")
    op.drop_index("ix_team_aliases_review_status", table_name="team_aliases")
    op.drop_index("ix_team_aliases_external_team_id", table_name="team_aliases")
    op.drop_table("team_aliases")
    op.drop_index("ix_matches_status_start_time", table_name="matches")
    op.drop_index("ix_matches_start_time", table_name="matches")
    op.drop_index("ix_matches_modellability", table_name="matches")
    op.drop_table("matches")
    op.drop_index("ix_historical_matches_match_date", table_name="historical_matches")
    op.drop_index("ix_historical_matches_home_team_id_match_date", table_name="historical_matches")
    op.drop_index("ix_historical_matches_away_team_id_match_date", table_name="historical_matches")
    op.drop_table("historical_matches")
    op.drop_index("ix_booking_codes_user_id_created_at", table_name="booking_codes")
    op.drop_index("ix_booking_codes_status", table_name="booking_codes")
    op.drop_table("booking_codes")
    op.drop_index("ix_wallet_transactions_user_id_created_at", table_name="wallet_transactions")
    op.drop_index("ix_wallet_transactions_state", table_name="wallet_transactions")
    op.drop_index(op.f("ix_wallet_transactions_created_at"), table_name="wallet_transactions")
    op.drop_table("wallet_transactions")
    op.drop_index("ix_teams_normalized_name", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_scans_user_id_created_at", table_name="scans")
    op.drop_index("ix_scans_status", table_name="scans")
    op.drop_table("scans")
    op.drop_index("ix_users_last_seen_at", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_model_versions_status", table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index("ix_competitions_has_historical_coverage", table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
