"""user activity and preferences

Revision ID: 31e4f0bc6ede
Revises: ec8ff4dc5e2a
Create Date: 2026-09-09 20:00:43.231551+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "31e4f0bc6ede"
down_revision: str | None = "ec8ff4dc5e2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_views",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("home_name", sa.String(length=128), nullable=False),
        sa.Column("away_name", sa.String(length=128), nullable=False),
        sa.Column("competition", sa.String(length=128), nullable=True),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_fixture_views_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_views")),
    )
    with op.batch_alter_table("fixture_views", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixture_views_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_fixture_views_fixture", ["provider_event_id"], unique=False)
        batch_op.create_index(
            "ix_fixture_views_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "saved_fixtures",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("home_name", sa.String(length=128), nullable=False),
        sa.Column("away_name", sa.String(length=128), nullable=False),
        sa.Column("competition", sa.String(length=128), nullable=True),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_fixtures_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_fixtures")),
        sa.UniqueConstraint("user_id", "provider_event_id", name="uq_saved_fixtures_user_fixture"),
    )
    with op.batch_alter_table("saved_fixtures", schema=None) as batch_op:
        batch_op.create_index("ix_saved_fixtures_user", ["user_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "settings", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preferences")),
        sa.UniqueConstraint("user_id", name="uq_user_preferences_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    with op.batch_alter_table("saved_fixtures", schema=None) as batch_op:
        batch_op.drop_index("ix_saved_fixtures_user")

    op.drop_table("saved_fixtures")
    with op.batch_alter_table("fixture_views", schema=None) as batch_op:
        batch_op.drop_index("ix_fixture_views_user_created")
        batch_op.drop_index("ix_fixture_views_fixture")
        batch_op.drop_index(batch_op.f("ix_fixture_views_created_at"))

    op.drop_table("fixture_views")
    # ### end Alembic commands ###
