"""add accepted terms version

Revision ID: 3df76d8d1672
Revises: 9371906473ab
Create Date: 2026-09-08 01:30:09.543224+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3df76d8d1672"
down_revision: str | None = "9371906473ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("accepted_terms_version", sa.String(length=16), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("accepted_terms_version")

    # ### end Alembic commands ###
