"""service selections snapshots and model only probabilities

Revision ID: 44deff8a342e
Revises: c89ed2f3976c
Create Date: 2026-09-12 21:20:32.531242+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "44deff8a342e"
down_revision: str | None = "c89ed2f3976c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_snapshots",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("fixtures_available", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fixtures_modelled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("services_run", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("services_qualified", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "coverage",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_snapshots")),
        sa.UniqueConstraint("snapshot_date", name="uq_daily_snapshot_date"),
    )
    with op.batch_alter_table("daily_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_daily_snapshots_date", ["snapshot_date"], unique=False)

    op.create_table(
        "selection_audits",
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "previous",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selection_audits")),
    )
    with op.batch_alter_table("selection_audits", schema=None) as batch_op:
        batch_op.create_index("ix_selection_audits_event", ["event"], unique=False)
        batch_op.create_index("ix_selection_audits_selection", ["selection_id"], unique=False)

    op.create_table(
        "service_selections",
        sa.Column("service_key", sa.String(length=32), nullable=False),
        sa.Column("service_label", sa.String(length=64), nullable=False),
        sa.Column("selection_date", sa.Date(), nullable=False),
        sa.Column("rank", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("home_name", sa.String(length=128), nullable=False),
        sa.Column("away_name", sa.String(length=128), nullable=False),
        sa.Column("competition", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("coverage", sa.String(length=24), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "components_used",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "factors",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("sample_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("corrected", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_selections")),
        sa.UniqueConstraint(
            "service_key", "selection_date", "rank", name="uq_service_selection_day"
        ),
    )
    with op.batch_alter_table("service_selections", schema=None) as batch_op:
        batch_op.create_index("ix_service_selections_date", ["selection_date"], unique=False)
        batch_op.create_index("ix_service_selections_fixture", ["provider_event_id"], unique=False)
        batch_op.create_index("ix_service_selections_market", ["market"], unique=False)
        batch_op.create_index("ix_service_selections_published", ["published_at"], unique=False)
        batch_op.create_index("ix_service_selections_service", ["service_key"], unique=False)
        batch_op.create_index("ix_service_selections_status", ["status"], unique=False)

    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "model_probabilities",
                sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
                server_default=sa.text("'{}'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "component_views",
                sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.drop_column("component_views")
        batch_op.drop_column("model_probabilities")

    with op.batch_alter_table("service_selections", schema=None) as batch_op:
        batch_op.drop_index("ix_service_selections_status")
        batch_op.drop_index("ix_service_selections_service")
        batch_op.drop_index("ix_service_selections_published")
        batch_op.drop_index("ix_service_selections_market")
        batch_op.drop_index("ix_service_selections_fixture")
        batch_op.drop_index("ix_service_selections_date")

    op.drop_table("service_selections")
    with op.batch_alter_table("selection_audits", schema=None) as batch_op:
        batch_op.drop_index("ix_selection_audits_selection")
        batch_op.drop_index("ix_selection_audits_event")

    op.drop_table("selection_audits")
    with op.batch_alter_table("daily_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_daily_snapshots_date")

    op.drop_table("daily_snapshots")
    # ### end Alembic commands ###
