"""analysis provenance

Revision ID: 5d211e716162
Revises: 31e4f0bc6ede
Create Date: 2026-09-09 20:07:44.842657+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5d211e716162"
down_revision: str | None = "31e4f0bc6ede"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # A NOT NULL column added to a populated table needs a value for the rows
    # that already exist. Autogenerate does not supply one, so the DDL fails on
    # any deployment that is not empty — which is every real one.
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provenance",
                sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
                nullable=False,
                server_default=sa.text("'{}'"),
            )
        )


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.drop_column("provenance")

    # ### end Alembic commands ###
