"""subscription state

Revision ID: 65cacc8c767b
Revises: 44deff8a342e
Create Date: 2026-09-13 16:19:12.320860+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65cacc8c767b"
down_revision: str | None = "44deff8a342e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subscription_tier",
                sa.String(length=16),
                server_default=sa.text("'free'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("subscription_expires_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("subscription_started_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("trial_used", sa.Boolean(), server_default=sa.text("(false)"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("trial_used")
        batch_op.drop_column("subscription_started_at")
        batch_op.drop_column("subscription_expires_at")
        batch_op.drop_column("subscription_tier")

    # ### end Alembic commands ###
