"""settlement source

Revision ID: 76d5808348bc
Revises: 6a5b14a78e6e
Create Date: 2026-09-09 06:34:15.666646+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76d5808348bc"
down_revision: str | None = "6a5b14a78e6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source", sa.String(length=16), server_default="live", nullable=False)
        )
        batch_op.create_index("ix_settled_predictions_source", ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_settled_predictions_source")
        batch_op.drop_column("source")

    # ### end Alembic commands ###
