"""fk covering indexes and wider expected value

Revision ID: 7c3af50a828e
Revises: 2a6b84e1ddb1
Create Date: 2026-09-08 01:05:08.282445+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7c3af50a828e"
down_revision: str | None = "2a6b84e1ddb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking_codes", schema=None) as batch_op:
        batch_op.create_index("ix_booking_codes_scan_id", ["scan_id"], unique=False)

    with op.batch_alter_table("historical_matches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_historical_matches_competition_id", ["competition_id"], unique=False
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index("ix_matches_away_team_id", ["away_team_id"], unique=False)
        batch_op.create_index("ix_matches_competition_id", ["competition_id"], unique=False)
        batch_op.create_index("ix_matches_home_team_id", ["home_team_id"], unique=False)

    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.alter_column(
            "expected_value",
            existing_type=sa.NUMERIC(precision=10, scale=8),
            type_=sa.Numeric(precision=14, scale=8),
            existing_nullable=False,
        )
        batch_op.create_index("ix_predictions_outcome_id", ["outcome_id"], unique=False)
        batch_op.create_index(
            "ix_predictions_reference_snapshot_id", ["reference_snapshot_id"], unique=False
        )
        batch_op.create_index(
            "ix_predictions_tradeable_snapshot_id", ["tradeable_snapshot_id"], unique=False
        )

    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index("ix_scans_model_version_id", ["model_version_id"], unique=False)

    with op.batch_alter_table("team_aliases", schema=None) as batch_op:
        batch_op.create_index("ix_team_aliases_team_id", ["team_id"], unique=False)

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index("ix_teams_competition_id", ["competition_id"], unique=False)

    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_wallet_transactions_parent_transaction_id", ["parent_transaction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_wallet_transactions_parent_transaction_id")

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index("ix_teams_competition_id")

    with op.batch_alter_table("team_aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_team_aliases_team_id")

    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index("ix_scans_model_version_id")

    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_predictions_tradeable_snapshot_id")
        batch_op.drop_index("ix_predictions_reference_snapshot_id")
        batch_op.drop_index("ix_predictions_outcome_id")
        batch_op.alter_column(
            "expected_value",
            existing_type=sa.Numeric(precision=14, scale=8),
            type_=sa.NUMERIC(precision=10, scale=8),
            existing_nullable=False,
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index("ix_matches_home_team_id")
        batch_op.drop_index("ix_matches_competition_id")
        batch_op.drop_index("ix_matches_away_team_id")

    with op.batch_alter_table("historical_matches", schema=None) as batch_op:
        batch_op.drop_index("ix_historical_matches_competition_id")

    with op.batch_alter_table("booking_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_booking_codes_scan_id")

    # ### end Alembic commands ###
