"""server defaults for non nullable columns

Revision ID: c5184dc0b3e7
Revises: 5d211e716162
Create Date: 2026-09-10 01:12:11.494102+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c5184dc0b3e7"
down_revision: str | None = "5d211e716162"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_ingestions", schema=None) as batch_op:
        batch_op.alter_column(
            "rejections",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.alter_column(
            "components_used",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'[]'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "favourite_won",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "markets",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "home_stats",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "away_stats",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "components_used",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'[]'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "components_dropped",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'[]'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.alter_column(
            "settings",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=sa.text("'{}'"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.alter_column(
            "settings",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "components_dropped",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "components_used",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "away_stats",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "home_stats",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "markets",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.alter_column(
            "favourite_won",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "components_used",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("dataset_ingestions", schema=None) as batch_op:
        batch_op.alter_column(
            "rejections",
            existing_type=sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###
