"""highlight tracks

Revision ID: c89ed2f3976c
Revises: 24a274993f49
Create Date: 2026-09-10 22:19:41.459444+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c89ed2f3976c"
down_revision: str | None = "24a274993f49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight_selections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "track", sa.String(length=24), server_default=sa.text("'sharp'"), nullable=False
            )
        )
        batch_op.drop_constraint("uq_highlight_fixture_market", type_="unique")
        batch_op.create_unique_constraint(
            "uq_highlight_fixture_market",
            ["provider_event_id", "market", "outcome", "source", "track"],
        )
        batch_op.create_index("ix_highlight_selections_track", ["track"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight_selections", schema=None) as batch_op:
        batch_op.drop_index("ix_highlight_selections_track")
        batch_op.drop_constraint("uq_highlight_fixture_market", type_="unique")
        batch_op.create_unique_constraint(
            "uq_highlight_fixture_market", ["provider_event_id", "market", "outcome", "source"]
        )
        batch_op.drop_column("track")

    # ### end Alembic commands ###
