"""widen provider event ids

Revision ID: ec8ff4dc5e2a
Revises: 76d5808348bc
Create Date: 2026-09-09 08:27:13.971441+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec8ff4dc5e2a"
down_revision: str | None = "76d5808348bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.alter_column(
            "provider_event_id",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "provider_event_id",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_analyses", schema=None) as batch_op:
        batch_op.alter_column(
            "provider_event_id",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    with op.batch_alter_table("settled_predictions", schema=None) as batch_op:
        batch_op.alter_column(
            "provider_event_id",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
